## Arewa Data Science Academy
### Deep Learning Cohort1.0

#### Name: Surajo Nuhu Umar
#### Email: surajonuhuumar@gmail.com
#### Title: Week 1 Solution

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor

tensor_1 = torch.rand(7,7)
tensor_1

tensor([[0.2940, 0.8299, 0.6792, 0.9208, 0.8228, 0.7315, 0.3057],
        [0.0248, 0.1312, 0.1652, 0.4008, 0.8435, 0.6904, 0.1486],
        [0.8909, 0.6235, 0.2140, 0.2473, 0.7920, 0.4218, 0.4465],
        [0.8088, 0.3090, 0.7779, 0.1916, 0.8719, 0.2439, 0.4705],
        [0.2654, 0.4865, 0.7286, 0.6788, 0.6577, 0.7617, 0.4524],
        [0.8111, 0.6503, 0.4439, 0.5978, 0.4088, 0.7202, 0.4353],
        [0.6706, 0.8436, 0.7319, 0.5889, 0.2605, 0.4247, 0.7329]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor_2 = torch.rand(1,7)


# Perform matrix multiplication 
result = torch.mm(tensor_1, tensor_2.T)
result

tensor([[1.3459],
        [0.5390],
        [1.4728],
        [1.1626],
        [1.0536],
        [1.5303],
        [1.4612]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.random.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand(7,7)
tensor_2 = torch.rand(1,7)


# Matrix multiply tensors
result_2 = torch.mm(tensor_1, tensor_2.T)
result_2

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.manual_seed(1234)



# Check for access to GPU 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# Create two random tensors on GPU
tensor_1 = torch.rand(2,3).to(device)
tensor_2 = torch.rand(2,3).to(device)
tensor_1, tensor_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [15]:
# Perform matmul on tensor_A and tensor_B
result = torch.mm(tensor_1, tensor_2.T)
result

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
max_val = torch.max(result)

# Find min
min_val = torch.min(result)

max_val, min_val

(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
arg_max = torch.argmax(result)


# Find arg min
arg_min = torch.argmin(result)

arg_max, arg_min


(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
squeezed_torch = torch.squeeze(tensor)


# Print out tensors and their shapes
tensor, tensor.shape,squeezed_torch, squeezed_torch.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))